package POM;


import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

import org.openqa.selenium.WebDriver;

public class BasePage {
	
	protected String getTranslation(String value) throws IOException {
		
		Properties p = new Properties();
		p.load(new FileReader(
				"C:/Users/sumancb/git/IndiaShop/India/src/test/java/property/catalog.properties"));
		return p.getProperty(value);
	}
			

	public static WebDriver driver;
	public static String[] qty = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10+" };
	public static String[] allproducts = { "ACTIVATE (30 SACHETS)", "BALANCE (30 SACHETS)", "BIOS LIFE COFFEE MIX (30 SACHETS)", "BIOS LIFE SLIM (30 SACHETS)", "BIOSLIFE AIR", "BLENDER BOTTLE W/AGITATOR", "CALCIUM MAGNESIUM COMPLEX (30 SACHETS)",
			"CLEAR START KIT - LIFIBER (30 SACHETS)+NATURE'S TEA (30 SACHETS)+PARAWAY PLUS (150 CAPSULES)", "ENRICH (500 GMS)", "KIDDO (16 SACHETS)", "LC BASE (20 SACHETS)", "LEAN COMPLETE (25 SACHETS)", "LIFIBER (28 SACHETS)", "NATURE'S TEA (30 SACHETS)",
			"NEIGENE COLLAGEN PLUS (30 SACHETS)", "PARAWAY PLUS (150 CAPSULES)", "PREMIUM MATCHA (10 SACHETS)",
			"PREMIUM SUPER CHLOROPHYLL (45 SERVINGS)", "SUPER CHLOROPHYLL PACK", "UNICITY CATALOGUE IN"};
	public static String[] products = { "ACTIVATE (30 SACHETS)", "BALANCE (30 SACHETS)", "BIOS LIFE COFFEE MIX (30 SACHETS)", "BIOS LIFE SLIM (30 SACHETS)", "BIOSLIFE AIR", "CALCIUM MAGNESIUM COMPLEX (30 SACHETS)",
			"CLEAR START KIT - LIFIBER (30 SACHETS)+NATURE'S TEA (30 SACHETS)+PARAWAY PLUS (150 CAPSULES)", "ENRICH (500 GMS)", "KIDDO (16 SACHETS)", "LC BASE (20 SACHETS)", "LEAN COMPLETE (25 SACHETS)", "LIFIBER (28 SACHETS)", "NATURE'S TEA (30 SACHETS)",
			"NEIGENE COLLAGEN PLUS (30 SACHETS)", "PARAWAY PLUS (150 CAPSULES)", "PREMIUM MATCHA (10 SACHETS)",
			"PREMIUM SUPER CHLOROPHYLL (45 SERVINGS)", "SUPER CHLOROPHYLL PACK", "UNICITY CATALOGUE IN"};
	public static String[] accessories = { "BLENDER BOTTLE W/AGITATOR",};
	
	public static String[] retailallproducts = {"ACTIVATE (30 SACHETS)", "BALANCE (30 SACHETS)", "BIOS LIFE COFFEE MIX (30 SACHETS)", "BIOS LIFE SLIM (30 SACHETS)", "BIOSLIFE AIR", "BLENDER BOTTLE W/AGITATOR", "CALCIUM MAGNESIUM COMPLEX (30 SACHETS)",
			"CLEAR START KIT - LIFIBER (30 SACHETS)+NATURE'S TEA (30 SACHETS)+PARAWAY PLUS (150 CAPSULES)", "ENRICH (500 GMS)", "KIDDO (16 SACHETS)", "LC BASE (20 SACHETS)", "LEAN COMPLETE (25 SACHETS)", "LIFIBER (28 SACHETS)", "NATURE'S TEA (30 SACHETS)",
			"NEIGENE COLLAGEN PLUS (30 SACHETS)", "PARAWAY PLUS (150 CAPSULES)", "PREMIUM MATCHA (10 SACHETS)",
			"PREMIUM SUPER CHLOROPHYLL (45 SERVINGS)"};
	public static String[] retailproducts = { "ACTIVATE (30 SACHETS)", "BALANCE (30 SACHETS)", "BIOS LIFE COFFEE MIX (30 SACHETS)", "BIOS LIFE SLIM (30 SACHETS)", "BIOSLIFE AIR", "CALCIUM MAGNESIUM COMPLEX (30 SACHETS)",
			"CLEAR START KIT - LIFIBER (30 SACHETS)+NATURE'S TEA (30 SACHETS)+PARAWAY PLUS (150 CAPSULES)", "ENRICH (500 GMS)", "KIDDO (16 SACHETS)", "LC BASE (20 SACHETS)", "LEAN COMPLETE (25 SACHETS)", "LIFIBER (28 SACHETS)", "NATURE'S TEA (30 SACHETS)",
			"NEIGENE COLLAGEN PLUS (30 SACHETS)", "PARAWAY PLUS (150 CAPSULES)", "PREMIUM MATCHA (10 SACHETS)",
			"PREMIUM SUPER CHLOROPHYLL (45 SERVINGS)"};
	public static String[] retailaccessories = { "BLENDER BOTTLE W/AGITATOR"};
	
	public static Map<String, String> productdetails = new HashMap<String, String>();
	public static Map<String, String> userdata = new HashMap<String, String>();	
}
